In [2]:
import pandas as pd
import numpy as np

url = "https://gist.githubusercontent.com/meperezcuello/82a9f1c1c473d6585e750ad2e3c05a41/raw/d42d226d0dd64e7f5395a0eec1b9190a10edbc03/Medical_Cost.csv"

In [3]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from scripts import project_functions
df = project_functions.load_and_process(url)
df.head(20)

,Age,Sex,BMI,Children,Smoker,Region,Charges,Body_Shape
0,19,female,27.900,0,yes,southwest,16884.92400,Class 1 Obesity
1,18,male,33.770,1,no,southeast,1725.55230,Class 2 Obesity
2,28,male,33.000,3,no,southeast,4449.46200,Class 2 Obesity
3,33,male,22.705,0,no,northwest,21984.47061,Normal Weight
4,32,male,28.880,0,no,northwest,3866.85520,Class 1 Obesity
5,31,female,25.740,0,no,southeast,3756.62160,Over Weight
6,46,female,33.440,1,no,southeast,8240.58960,Class 2 Obesity
7,37,female,27.740,3,no,northwest,7281.50560,Class 1 Obesity
8,37,male,29.830,2,no,northeast,6406.41070,Class 1 Obesity
9,60,female,25.840,0,no,northwest,28923.13692,Over Weight
10,25,male,26.220,0,no,northeast,2721.32080,Over Weight
11,62,female,26.290,0,yes,southeast,27808.72510,Over Weight
12,23,male,34.400,0,no,southwest,1826.84300,Class 2 Obesity
13,56,female,39.820,0,no,southeast,11090.71780,Class 3 Obesity
14,27,male,42.130,0,yes,southeast,39611.75770,Class 3 Obesity
15,19,male,24.600,1,no,southwest,1837.23700,Over Weight
16,52,female,30.780,1,no,northeast,10797.33620,Class 1 Obesity
17,23,male,23.845,0,no,northeast,2395.17155,Over Weight
18,56,male,40.300,0,no,southwest,10602.38500,Class 3 Obesity
19,30,male,35.300,0,yes,southwest,36837.46700,Class 2 Obesity